#!/bin/bash 
#/etc/vpssim/menu/inc/vpssim-cai-dat-glibc-khong-duoc-ma-hoa
if [ ! -d /etc/vpssim/.tmp ]; then
mkdir -p /etc/vpssim/.tmp
fi
yum install -y kernel-headers
arch=`uname -m`
if [ "$arch" = "x86_64" ]; then
XXX=x86_64
YYY=x86_64
else
XXX=i686
YYY=i386
fi

if [ "$(rpm -qf --queryformat="%{VERSION}" /etc/redhat-release)" == "6" ]; then 

ketnoi=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "http://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-x86_64/glibc-2.17-55.fc20/glibc-2.17-55.el6.x86_64.rpm")

if [[ "$ketnoi" != "000" ]]; then
wget http://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-$YYY/glibc-2.17-55.fc20/glibc-2.17-55.el6.$XXX.rpm
wget http://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-$YYY/glibc-2.17-55.fc20/glibc-common-2.17-55.el6.$XXX.rpm
wget http://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-$YYY/glibc-2.17-55.fc20/glibc-devel-2.17-55.el6.$XXX.rpm
wget http://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-$YYY/glibc-2.17-55.fc20/glibc-headers-2.17-55.el6.$XXX.rpm
else
wget https://vpssim.com/script/vpssim/Softwear/glibc_2.17/glibc-2.17-55.el6.$XXX.rpm
wget https://vpssim.com/script/vpssim/Softwear/glibc_2.17/glibc-common-2.17-55.el6.$XXX.rpm
wget https://vpssim.com/script/vpssim/Softwear/glibc_2.17/glibc-devel-2.17-55.el6.$XXX.rpm
wget https://vpssim.com/script/vpssim/Softwear/glibc_2.17/glibc-headers-2.17-55.el6.$XXX.rpm
fi
sudo rpm -Uvh glibc-2.17-55.el6.$XXX.rpm \
glibc-common-2.17-55.el6.$XXX.rpm \
glibc-devel-2.17-55.el6.$XXX.rpm \
glibc-headers-2.17-55.el6.$XXX.rpm #--force --nodeps
rm -rf /etc/vpssim/.tmp/asnhzad
ldd --version | grep "2.17" > /etc/vpssim/.tmp/asnhzad
if [ "$(wc -c < /etc/vpssim/.tmp/asnhzad)" -lt "1" ]; then
sudo rpm -Uvh glibc-2.17-55.el6.$XXX.rpm \
glibc-common-2.17-55.el6.$XXX.rpm \
glibc-devel-2.17-55.el6.$XXX.rpm \
glibc-headers-2.17-55.el6.$XXX.rpm --force --nodeps
fi
rm -rf /root/glibc*
fi

if [ "$(rpm -qf --queryformat="%{VERSION}" /etc/redhat-release)" == "7" ]; then 
ketnoi=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "http://cbs.centos.org/kojifiles/packages/glibc/2.22.90/21.el7/x86_64/glibc-2.22.90-21.el7.x86_64.rpm")
if [[ "$ketnoi" != "000" ]]; then
wget http://cbs.centos.org/kojifiles/packages/glibc/2.22.90/21.el7/x86_64/glibc-2.22.90-21.el7.x86_64.rpm
wget http://cbs.centos.org/kojifiles/packages/glibc/2.22.90/21.el7/x86_64/glibc-common-2.22.90-21.el7.x86_64.rpm
wget http://cbs.centos.org/kojifiles/packages/glibc/2.22.90/21.el7/x86_64/glibc-devel-2.22.90-21.el7.x86_64.rpm
wget http://cbs.centos.org/kojifiles/packages/glibc/2.22.90/21.el7/x86_64/glibc-headers-2.22.90-21.el7.x86_64.rpm
else
wget https://vpssim.com/script/vpssim/Softwear/glibc_2.22/glibc-2.22.90-21.el7.x86_64.rpm
wget https://vpssim.com/script/vpssim/Softwear/glibc_2.22/glibc-common-2.22.90-21.el7.x86_64.rpm
wget https://vpssim.com/script/vpssim/Softwear/glibc_2.22/glibc-devel-2.22.90-21.el7.x86_64.rpm
wget https://vpssim.com/script/vpssim/Softwear/glibc_2.22/glibc-headers-2.22.90-21.el7.x86_64.rpm
fi
sudo rpm -Uvh glibc-2.22.90-21.el7.x86_64.rpm \
glibc-common-2.22.90-21.el7.x86_64.rpm \
glibc-devel-2.22.90-21.el7.x86_64.rpm \
glibc-headers-2.22.90-21.el7.x86_64.rpm
rm -rf /etc/vpssim/.tmp/asnhzad
ldd --version | grep "2.22" > /etc/vpssim/.tmp/asnhzad
if [ "$(wc -c < /etc/vpssim/.tmp/asnhzad)" -lt "1" ]; then
sudo rpm -Uvh glibc-2.22.90-21.el7.x86_64.rpm \
glibc-common-2.22.90-21.el7.x86_64.rpm \
glibc-devel-2.22.90-21.el7.x86_64.rpm \
glibc-headers-2.22.90-21.el7.x86_64.rpm --force --nodeps
fi
rm -rf /etc/vpssim/.tmp/asnhzad 
rm -rf /root/glibc*
fi


